alumno = [
    # Alumnos de la lista verde
    {'id': 1001, 'nombre': 'Juan', 'apellido': 'González', 'genero': 'M', 'carrera': 'Ing. en Sistemas', 'actividad': 'futbol', 'tribu': 'verde'},
    {'id': 1002, 'nombre': 'María', 'apellido': 'Rodríguez', 'genero': 'F', 'carrera': 'Abogacía', 'actividad': 'coreografia', 'tribu': 'verde'},
    {'id': 1003, 'nombre': 'Carlos', 'apellido': 'Gómez', 'genero': 'M', 'carrera': 'Medicina', 'actividad': 'ajedrez', 'tribu': 'verde'},
    {'id': 1004, 'nombre': 'Ana', 'apellido': 'Fernández', 'genero': 'F', 'carrera': 'Arquitectura', 'actividad': 'ping-pong', 'tribu': 'verde'},
    {'id': 1005, 'nombre': 'Luis', 'apellido': 'López', 'genero': 'M', 'carrera': 'Psicología', 'actividad': 'truco', 'tribu': 'verde'},
    {'id': 1006, 'nombre': 'Laura', 'apellido': 'Díaz', 'genero': 'F', 'carrera': 'Contador Público', 'actividad': 'foto', 'tribu': 'verde'},
    {'id': 1007, 'nombre': 'Pedro', 'apellido': 'Martínez', 'genero': 'M', 'carrera': 'Diseño Gráfico', 'actividad': 'basquet', 'tribu': 'verde'},
    {'id': 1008, 'nombre': 'Sofía', 'apellido': 'Pérez', 'genero': 'F', 'carrera': 'Lic. en Letras', 'actividad': 'talento', 'tribu': 'verde'},
    {'id': 1009, 'nombre': 'Diego', 'apellido': 'García', 'genero': 'M', 'carrera': 'Ing. Civil', 'actividad': 'volley', 'tribu': 'verde'},
    {'id': 1010, 'nombre': 'Valentina', 'apellido': 'Sánchez', 'genero': 'F', 'carrera': 'Marketing', 'actividad': 'circuito de habilidades', 'tribu': 'verde'},
    {'id': 1011, 'nombre': 'Miguel', 'apellido': 'Romero', 'genero': 'M', 'carrera': 'Ing. en Sistemas', 'actividad': 'gimnasio', 'tribu': 'verde'},
    {'id': 1012, 'nombre': 'Camila', 'apellido': 'Sosa', 'genero': 'F', 'carrera': 'Abogacía', 'actividad': 'handball', 'tribu': 'verde'},
    {'id': 1013, 'nombre': 'Javier', 'apellido': 'Álvarez', 'genero': 'M', 'carrera': 'Medicina', 'actividad': 'quemado', 'tribu': 'verde'},
    {'id': 1014, 'nombre': 'Lucía', 'apellido': 'Torres', 'genero': 'F', 'carrera': 'Arquitectura', 'actividad': 'futbol tenis', 'tribu': 'verde'},
    {'id': 1015, 'nombre': 'Fernando', 'apellido': 'Ruiz', 'genero': 'M', 'carrera': 'Psicología', 'actividad': 'tejo', 'tribu': 'verde'},
    {'id': 1016, 'nombre': 'Martina', 'apellido': 'Ramírez', 'genero': 'F', 'carrera': 'Contador Público', 'actividad': 'jabalina', 'tribu': 'verde'},
    {'id': 1017, 'nombre': 'José', 'apellido': 'Flores', 'genero': 'M', 'carrera': 'Diseño Gráfico', 'actividad': 'tutti frutti', 'tribu': 'verde'},
    {'id': 1018, 'nombre': 'Paula', 'apellido': 'Acosta', 'genero': 'F', 'carrera': 'Lic. en Letras', 'actividad': 'futbol', 'tribu': 'verde'},
    {'id': 1019, 'nombre': 'Manuel', 'apellido': 'Benítez', 'genero': 'M', 'carrera': 'Ing. Civil', 'actividad': 'ping-pong', 'tribu': 'verde'},
    {'id': 1020, 'nombre': 'Gabriela', 'apellido': 'Medina', 'genero': 'F', 'carrera': 'Marketing', 'actividad': 'ajedrez', 'tribu': 'verde'},
    {'id': 1021, 'nombre': 'Andrés', 'apellido': 'Herrera', 'genero': 'M', 'carrera': 'Ing. en Sistemas', 'actividad': 'truco', 'tribu': 'verde'},
    {'id': 1022, 'nombre': 'Isabella', 'apellido': 'Gutiérrez', 'genero': 'F', 'carrera': 'Abogacía', 'actividad': 'basquet', 'tribu': 'verde'},
    {'id': 1023, 'nombre': 'David', 'apellido': 'Pereyra', 'genero': 'M', 'carrera': 'Medicina', 'actividad': 'foto', 'tribu': 'verde'},
    {'id': 1024, 'nombre': 'Daniela', 'apellido': 'Rojas', 'genero': 'F', 'carrera': 'Arquitectura', 'actividad': 'coreografia', 'tribu': 'verde'},
    {'id': 1025, 'nombre': 'Sergio', 'apellido': 'Molina', 'genero': 'M', 'carrera': 'Psicología', 'actividad': 'talento', 'tribu': 'verde'},
    {'id': 1026, 'nombre': 'Carolina', 'apellido': 'Castro', 'genero': 'F', 'carrera': 'Contador Público', 'actividad': 'gimnasio', 'tribu': 'verde'},
    {'id': 1027, 'nombre': 'Jorge', 'apellido': 'Ortiz', 'genero': 'M', 'carrera': 'Diseño Gráfico', 'actividad': 'circuito de habilidades', 'tribu': 'verde'},
    {'id': 1028, 'nombre': 'Verónica', 'apellido': 'Silva', 'genero': 'F', 'carrera': 'Lic. en Letras', 'actividad': 'volley', 'tribu': 'verde'},
    {'id': 1029, 'nombre': 'Ricardo', 'apellido': 'Núñez', 'genero': 'M', 'carrera': 'Ing. Civil', 'actividad': 'handball', 'tribu': 'verde'},
    {'id': 1030, 'nombre': 'Patricia', 'apellido': 'Luna', 'genero': 'F', 'carrera': 'Marketing', 'actividad': 'quemado', 'tribu': 'verde'},
    {'id': 1031, 'nombre': 'Emiliano', 'apellido': 'Juárez', 'genero': 'M', 'carrera': 'Ing. en Sistemas', 'actividad': 'futbol tenis', 'tribu': 'verde'},
    {'id': 1032, 'nombre': 'Julieta', 'apellido': 'Paz', 'genero': 'F', 'carrera': 'Abogacía', 'actividad': 'tejo', 'tribu': 'verde'},
    {'id': 1033, 'nombre': 'Maximiliano', 'apellido': 'Vera', 'genero': 'M', 'carrera': 'Medicina', 'actividad': 'jabalina', 'tribu': 'verde'},
    {'id': 1034, 'nombre': 'Agustina', 'apellido': 'Domínguez', 'genero': 'F', 'carrera': 'Arquitectura', 'actividad': 'tutti frutti', 'tribu': 'verde'},
    {'id': 1035, 'nombre': 'Francisco', 'apellido': 'Muñoz', 'genero': 'M', 'carrera': 'Psicología', 'actividad': 'futbol', 'tribu': 'verde'},
    {'id': 1036, 'nombre': 'Florencia', 'apellido': 'Moreno', 'genero': 'F', 'carrera': 'Contador Público', 'actividad': 'ping-pong', 'tribu': 'verde'},
    {'id': 1037, 'nombre': 'Matías', 'apellido': 'Iglesias', 'genero': 'M', 'carrera': 'Diseño Gráfico', 'actividad': 'ajedrez', 'tribu': 'verde'},
    {'id': 1038, 'nombre': 'Micaela', 'apellido': 'Blanco', 'genero': 'F', 'carrera': 'Lic. en Letras', 'actividad': 'truco', 'tribu': 'verde'},
    {'id': 1039, 'nombre': 'Nicolás', 'apellido': 'Navarro', 'genero': 'M', 'carrera': 'Ing. Civil', 'actividad': 'basquet', 'tribu': 'verde'},
    {'id': 1040, 'nombre': 'Rocío', 'apellido': 'Quiroga', 'genero': 'F', 'carrera': 'Marketing', 'actividad': 'foto', 'tribu': 'verde'},
    {'id': 1041, 'nombre': 'Lautaro', 'apellido': 'Castillo', 'genero': 'M', 'carrera': 'Ing. en Sistemas', 'actividad': 'coreografia', 'tribu': 'verde'},
    {'id': 1042, 'nombre': 'Victoria', 'apellido': 'Vega', 'genero': 'F', 'carrera': 'Abogacía', 'actividad': 'talento', 'tribu': 'verde'},
    {'id': 1043, 'nombre': 'Bruno', 'apellido': 'Ramos', 'genero': 'M', 'carrera': 'Medicina', 'actividad': 'gimnasio', 'tribu': 'verde'},
    {'id': 1044, 'nombre': 'Catalina', 'apellido': 'Fuentes', 'genero': 'F', 'carrera': 'Arquitectura', 'actividad': 'circuito de habilidades', 'tribu': 'verde'},
    {'id': 1045, 'nombre': 'Tomás', 'apellido': 'Méndez', 'genero': 'M', 'carrera': 'Psicología', 'actividad': 'volley', 'tribu': 'verde'},
    {'id': 1046, 'nombre': 'Abril', 'apellido': 'Leiva', 'genero': 'F', 'carrera': 'Contador Público', 'actividad': 'handball', 'tribu': 'verde'},
    {'id': 1047, 'nombre': 'Santino', 'apellido': 'Cabrera', 'genero': 'M', 'carrera': 'Diseño Gráfico', 'actividad': 'quemado', 'tribu': 'verde'},
    {'id': 1048, 'nombre': 'Zoe', 'apellido': 'Godoy', 'genero': 'F', 'carrera': 'Lic. en Letras', 'actividad': 'futbol tenis', 'tribu': 'verde'},
    {'id': 1049, 'nombre': 'Lucas', 'apellido': 'Ferreyra', 'genero': 'M', 'carrera': 'Ing. Civil', 'actividad': 'tejo', 'tribu': 'verde'},
    {'id': 1050, 'nombre': 'Mora', 'apellido': 'Peralta', 'genero': 'F', 'carrera': 'Marketing', 'actividad': 'jabalina', 'tribu': 'verde'},

    # Alumnos de la lista azul
    {'id': 2001, 'nombre': 'Mateo', 'apellido': 'Ríos', 'genero': 'M', 'carrera': 'Medicina', 'actividad': 'tutti frutti', 'tribu': 'azul'},
    {'id': 2002, 'nombre': 'Emilia', 'apellido': 'Figueroa', 'genero': 'F', 'carrera': 'Psicología', 'actividad': 'circuito de habilidades', 'tribu': 'azul'},
    {'id': 2003, 'nombre': 'Joaquín', 'apellido': 'Correa', 'genero': 'M', 'carrera': 'Abogacía', 'actividad': 'gimnasio', 'tribu': 'azul'},
    {'id': 2004, 'nombre': 'Renata', 'apellido': 'Morales', 'genero': 'F', 'carrera': 'Ing. en Sistemas', 'actividad': 'futbol', 'tribu': 'azul'},
    {'id': 2005, 'nombre': 'Bautista', 'apellido': 'Vázquez', 'genero': 'M', 'carrera': 'Arquitectura', 'actividad': 'ping-pong', 'tribu': 'azul'},
    {'id': 2006, 'nombre': 'Elena', 'apellido': 'Soria', 'genero': 'F', 'carrera': 'Contador Público', 'actividad': 'coreografia', 'tribu': 'azul'},
    {'id': 2007, 'nombre': 'Felipe', 'apellido': 'Miranda', 'genero': 'M', 'carrera': 'Diseño Gráfico', 'actividad': 'ajedrez', 'tribu': 'azul'},
    {'id': 2008, 'nombre': 'Clara', 'apellido': 'Chávez', 'genero': 'F', 'carrera': 'Lic. en Letras', 'actividad': 'truco', 'tribu': 'azul'},
    {'id': 2009, 'nombre': 'Ignacio', 'apellido': 'Reyes', 'genero': 'M', 'carrera': 'Ing. Civil', 'actividad': 'foto', 'tribu': 'azul'},
    {'id': 2010, 'nombre': 'Olivia', 'apellido': 'Campos', 'genero': 'F', 'carrera': 'Marketing', 'actividad': 'basquet', 'tribu': 'azul'},
    {'id': 2011, 'nombre': 'Thiago', 'apellido': 'Giménez', 'genero': 'M', 'carrera': 'Medicina', 'actividad': 'talento', 'tribu': 'azul'},
    {'id': 2012, 'nombre': 'Josefina', 'apellido': 'Toledo', 'genero': 'F', 'carrera': 'Psicología', 'actividad': 'volley', 'tribu': 'azul'},
    {'id': 2013, 'nombre': 'Benjamín', 'apellido': 'Bravo', 'genero': 'M', 'carrera': 'Abogacía', 'actividad': 'handball', 'tribu': 'azul'},
    {'id': 2014, 'nombre': 'Delfina', 'apellido': 'Montenegro', 'genero': 'F', 'carrera': 'Ing. en Sistemas', 'actividad': 'quemado', 'tribu': 'azul'},
    {'id': 2015, 'nombre': 'Alejandro', 'apellido': 'Costas', 'genero': 'M', 'carrera': 'Arquitectura', 'actividad': 'futbol tenis', 'tribu': 'azul'},
    {'id': 2016, 'nombre': 'Bianca', 'apellido': 'Arias', 'genero': 'F', 'carrera': 'Contador Público', 'actividad': 'tejo', 'tribu': 'azul'},
    {'id': 2017, 'nombre': 'Daniel', 'apellido': 'Romano', 'genero': 'M', 'carrera': 'Diseño Gráfico', 'actividad': 'jabalina', 'tribu': 'azul'},
    {'id': 2018, 'nombre': 'Guillermina', 'apellido': 'Ponce', 'genero': 'F', 'carrera': 'Lic. en Letras', 'actividad': 'tutti frutti', 'tribu': 'azul'},
    {'id': 2019, 'nombre': 'Esteban', 'apellido': 'Carrizo', 'genero': 'M', 'carrera': 'Ing. Civil', 'actividad': 'circuito de habilidades', 'tribu': 'azul'},
    {'id': 2020, 'nombre': 'Martina', 'apellido': 'Gallardo', 'genero': 'F', 'carrera': 'Marketing', 'actividad': 'gimnasio', 'tribu': 'azul'},
    {'id': 2021, 'nombre': 'Sebastián', 'apellido': 'Ledesma', 'genero': 'M', 'carrera': 'Medicina', 'actividad': 'futbol', 'tribu': 'azul'},
    {'id': 2022, 'nombre': 'Malena', 'apellido': 'Barrios', 'genero': 'F', 'carrera': 'Psicología', 'actividad': 'ping-pong', 'tribu': 'azul'},
    {'id': 2023, 'nombre': 'Agustín', 'apellido': 'Márquez', 'genero': 'M', 'carrera': 'Abogacía', 'actividad': 'coreografia', 'tribu': 'azul'},
    {'id': 2024, 'nombre': 'Rosario', 'apellido': 'Guzmán', 'genero': 'F', 'carrera': 'Ing. en Sistemas', 'actividad': 'ajedrez', 'tribu': 'azul'},
    {'id': 2025, 'nombre': 'Rodrigo', 'apellido': 'Cáceres', 'genero': 'M', 'carrera': 'Arquitectura', 'actividad': 'truco', 'tribu': 'azul'},
    {'id': 2026, 'nombre': 'Pilar', 'apellido': 'Aguirre', 'genero': 'F', 'carrera': 'Contador Público', 'actividad': 'foto', 'tribu': 'azul'},
    {'id': 2027, 'nombre': 'Federico', 'apellido': 'Escobar', 'genero': 'M', 'carrera': 'Diseño Gráfico', 'actividad': 'basquet', 'tribu': 'azul'},
    {'id': 2028, 'nombre': 'Justina', 'apellido': 'Bustos', 'genero': 'F', 'carrera': 'Lic. en Letras', 'actividad': 'talento', 'tribu': 'azul'},
    {'id': 2029, 'nombre': 'Leonardo', 'apellido': 'Paez', 'genero': 'M', 'carrera': 'Ing. Civil', 'actividad': 'volley', 'tribu': 'azul'},
    {'id': 2030, 'nombre': 'Alma', 'apellido': 'Salazar', 'genero': 'F', 'carrera': 'Marketing', 'actividad': 'handball', 'tribu': 'azul'},
    {'id': 2031, 'nombre': 'Iván', 'apellido': 'Farias', 'genero': 'M', 'carrera': 'Medicina', 'actividad': 'quemado', 'tribu': 'azul'},
    {'id': 2032, 'nombre': 'Lourdes', 'apellido': 'Orellana', 'genero': 'F', 'carrera': 'Psicología', 'actividad': 'futbol tenis', 'tribu': 'azul'},
    {'id': 2033, 'nombre': 'Hernán', 'apellido': 'Ayala', 'genero': 'M', 'carrera': 'Abogacía', 'actividad': 'tejo', 'tribu': 'azul'},
    {'id': 2034, 'nombre': 'Antonella', 'apellido': 'Pinto', 'genero': 'F', 'carrera': 'Ing. en Sistemas', 'actividad': 'jabalina', 'tribu': 'azul'},
    {'id': 2035, 'nombre': 'Gonzalo', 'apellido': 'Calvo', 'genero': 'M', 'carrera': 'Arquitectura', 'actividad': 'tutti frutti', 'tribu': 'azul'},
    {'id': 2036, 'nombre': 'Candelaria', 'apellido': 'Lucero', 'genero': 'F', 'carrera': 'Contador Público', 'actividad': 'circuito de habilidades', 'tribu': 'azul'},
    {'id': 2037, 'nombre': 'Mariano', 'apellido': 'Roldán', 'genero': 'M', 'carrera': 'Diseño Gráfico', 'actividad': 'gimnasio', 'tribu': 'azul'},
    {'id': 2038, 'nombre': 'Valeria', 'apellido': 'Santillán', 'genero': 'F', 'carrera': 'Lic. en Letras', 'actividad': 'futbol', 'tribu': 'azul'},
    {'id': 2039, 'nombre': 'Facundo', 'apellido': 'Coronel', 'genero': 'M', 'carrera': 'Ing. Civil', 'actividad': 'ping-pong', 'tribu': 'azul'},
    {'id': 2040, 'nombre': 'Celeste', 'apellido': 'Ibarra', 'genero': 'F', 'carrera': 'Marketing', 'actividad': 'coreografia', 'tribu': 'azul'},
    {'id': 2041, 'nombre': 'Julián', 'apellido': 'Moyano', 'genero': 'M', 'carrera': 'Medicina', 'actividad': 'ajedrez', 'tribu': 'azul'},
    {'id': 2042, 'nombre': 'Manuela', 'apellido': 'Villalba', 'genero': 'F', 'carrera': 'Psicología', 'actividad': 'truco', 'tribu': 'azul'},
    {'id': 2043, 'nombre': 'Franco', 'apellido': 'Suárez', 'genero': 'M', 'carrera': 'Abogacía', 'actividad': 'foto', 'tribu': 'azul'},
    {'id': 2044, 'nombre': 'Milagros', 'apellido': 'Ortega', 'genero': 'F', 'carrera': 'Ing. en Sistemas', 'actividad': 'basquet', 'tribu': 'azul'},
    {'id': 2045, 'nombre': 'Adrián', 'apellido': 'Soto', 'genero': 'M', 'carrera': 'Arquitectura', 'actividad': 'talento', 'tribu': 'azul'},
    {'id': 2046, 'nombre': 'Amanda', 'apellido': 'Franco', 'genero': 'F', 'carrera': 'Contador Público', 'actividad': 'volley', 'tribu': 'azul'},
    {'id': 2047, 'nombre': 'Enzo', 'apellido': 'Peralta', 'genero': 'M', 'carrera': 'Diseño Gráfico', 'actividad': 'handball', 'tribu': 'azul'},
    {'id': 2048, 'nombre': 'Amparo', 'apellido': 'Maidana', 'genero': 'F', 'carrera': 'Lic. en Letras', 'actividad': 'quemado', 'tribu': 'azul'},
    {'id': 2049, 'nombre': 'Simón', 'apellido': 'Rojas', 'genero': 'M', 'carrera': 'Ing. Civil', 'actividad': 'futbol tenis', 'tribu': 'azul'},
    {'id': 2050, 'nombre': 'Violeta', 'apellido': 'Gómez', 'genero': 'F', 'carrera': 'Marketing', 'actividad': 'tejo', 'tribu': 'azul'},
]